[package]
name = "rusty_z"
version = "0.0.1"
authors = [ "Stew <mckinnsb@gmail.com>" ]

[dependencies]
rand = "0.3.15"

[dependencies.webplatform]
git = "https://github.com/tcr/rust-webplatform"
 
[target.'cfg(not(target_os="emscripten"))'.dependencies]
termion = "1.1.4"
